# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-07 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_passout'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
