# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180320_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='fees',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='reviews',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='college',
            name='score',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='specialisation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
