# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_counsellor'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='ethnicity',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
