# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_college_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='ratings',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
