# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_college_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='ratings',
            field=models.IntegerField(),
        ),
    ]
